### ISSUE TITLE
Memory Overflow no Convert

### ISSUE THREAD

**Issue by filipe-silva-27** [filipe-silva-27/ES-2023-2Sem-Sexta-Feira-LIGE-GrupoA#24]
A memória na leitura do ficheiro CSV rebenta quando este é muito grande. Possível causa: FileReader
Possíveis Soluções: Usar biblioteca do Maven, ou separar o ficheiro em partes.

**Comment by filipe-silva-27** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Conversão Horário [CSV-JSON]](https://trello.com/c/trN88DOj/30-convers%C3%A3o-hor%C3%A1rio-csv-json)

**Comment by kreativermario** [comment]
Resolvido com a utilização do CSVReader. O que estava a causar o programa freezar era as mensagens de debug do objeto horário.
