### ISSUE TITLE
Parece-me tudo bem exceto o Botão Voltar que dá um index out of bounds exception.

### ISSUE THREAD

**Issue by kreativermario** [filipe-silva-27/ES-2023-2Sem-Sexta-Feira-LIGE-GrupoA#4]
Parece-me tudo bem exceto o Botão Voltar que dá um index out of bounds exception.

_Originally posted by @kreativermario in https://github.com/filipe-silva-27/ES-2023-2Sem-Sexta-Feira-LIGE-GrupoA/pull/3#pullrequestreview-1376465067_

**Comment by kreativermario** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GUI de Interação com utilizador final](https://trello.com/c/HTpiYT6n/47-gui-de-intera%C3%A7%C3%A3o-com-utilizador-final)

**Comment by Ruisth23** [comment]
Corrigido, já não dá OutOfBounfException
